"""`dino_runtime.py` for an export bundle (doc 121), assembled from the app's own code.

A hand-written predict script would drift from the app, and a drifted one gives confident
wrong answers. So the runtime is the source of the functions inference itself uses —
preprocessing, the token split, the head modules, the decoders, the mapping back to the
picture — with the `app.*` imports removed, plus a small glue (`runtime_glue.tmpl`). A
parity test runs the generated file against the app.
"""

from __future__ import annotations

import inspect
from pathlib import Path
from types import ModuleType

from app.ml import backbone, preprocess
from app.ml.heads import builders, decode, modules
from app.ml.inference import geometry, payloads

HEADER = '''"""V-Rex model runtime — generated by the app at export time. Do not edit.

Everything the app does to run a trained head: preprocessing, the backbone's token split,
the head module, decoding, and mapping the result back onto the picture. The functions
below are the app's own source; only its imports were removed.
"""

from __future__ import annotations

import base64
import io
import json
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Literal

import numpy as np
import torch
from PIL import Image
from torch import Tensor, nn
from torchvision.ops import batched_nms

Box = tuple[float, float, float, float]
ResampleMode = Literal["nearest", "bilinear"]
DecodeFn = Callable[[dict[str, Tensor], int], dict[str, Tensor]]
'''

#: (module, names) in dependency order. A constant is written as its value; a function
#: or class as its source.
PIECES: tuple[tuple[ModuleType, tuple[str, ...]], ...] = (
    (backbone, ("FeatureShapeError", "BackboneFeatures", "_grid_dims", "_split_tokens")),
    (
        preprocess,
        (
            "PreprocessPlan",
            "GeometryTransform",
            "_letterbox",
            "_center_crop",
            "apply_geometry",
            "to_pixel_values",
        ),
    ),
    (
        modules,
        (
            "DETECTION_UPSAMPLE",
            "DETECTION_HIDDEN",
            "ClassificationHead",
            "DetectionHead",
            "SegmentationHead",
            "DepthHead",
            "upsample_logits",
            "decode_ltrb_to_boxes",
        ),
    ),
    (builders, ("_classifier", "_detector", "_segmenter", "_depth")),
    (
        decode,
        (
            "MAX_DETECTIONS",
            "NMS_IOU_THRESHOLD",
            "identity_decode",
            "_suppress_overlaps",
            "detection_decode",
        ),
    ),
    (geometry, ("invert_point", "invert_boxes", "invert_map")),
    (
        payloads,
        (
            "MAX_DISPLAY_BOXES",
            "MAX_PNG_CLASSES",
            "to_numpy",
            "encode_png",
            "encode_class_map",
            "build_payload",
            "labels_payload",
            "boxes_payload",
            "source_boxes_payload",
            "masks_payload",
            "depth_payload",
            "encode_depth_map",
        ),
    ),
)

#: The trainable head types the runtime can run, with their builder and decoder names.
SUPPORTED: dict[str, tuple[str, str]] = {
    "linear-classifier": ("_classifier", "identity_decode"),
    "dense-detector": ("_detector", "detection_decode"),
    "linear-segmenter": ("_segmenter", "identity_decode"),
    "linear-depth": ("_depth", "identity_decode"),
}


def _piece(module: ModuleType, name: str) -> str:
    value = getattr(module, name)
    if isinstance(value, (int, float, str, tuple)):
        return f"{name} = {value!r}"
    return inspect.getsource(value)


def runtime_source() -> str:
    """The whole `dino_runtime.py`."""
    parts = [HEADER]
    for module, names in PIECES:
        parts.append(f"# --- from {module.__name__} " + "-" * max(0, 60 - len(module.__name__)))
        parts.extend(_piece(module, name) for name in names)
    table = ",\n".join(
        f"    {head_type!r}: ({builder}, {decoder})"
        for head_type, (builder, decoder) in SUPPORTED.items()
    )
    note = "#: head type id → (builder, decoder), as the app's registry maps them."
    parts.append(f"{note}\nHEADS = {{\n{table},\n}}")
    parts.append(
        (Path(__file__).with_name("runtime_glue.tmpl"))
        .read_text(encoding="utf-8")
        .split("# --- glue ---", 1)[1]
    )
    return "\n\n".join(parts) + "\n"


__all__ = ["SUPPORTED", "runtime_source"]
